import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";

import { AvailabilityBadges } from "@/components/AvailabilityBadges";
import { type Runeword, runewords } from "@/data";
import { en } from "@/i18n/en";

describe("AvailabilityBadges", () => {
  it("renders patch and note for `Mosaic`, and nothing else", () => {
    const mosaic = named("Mosaic");

    render(<AvailabilityBadges runeword={mosaic} />);

    expect(
      screen.getByRole("img", { name: en.availability.patchMeaning("2.6") }),
    ).toHaveTextContent("2.6");
    expect(screen.getByRole("img", { name: mosaic.note })).toHaveTextContent(
      en.availability.noteMarker,
    );
    // Two badges, not three. `Mosaic` is the record that carries the most
    // availability there is to carry, so it is where a third would show up.
    expect(screen.getAllByRole("img")).toHaveLength(2);
  });

  it("states a badge's meaning rather than the marker it draws", () => {
    render(<AvailabilityBadges runeword={named("Mosaic")} />);

    const patch = screen.getByRole("img", {
      name: en.availability.patchMeaning("2.6"),
    });

    expect(patch).not.toHaveAccessibleName("2.6");
    // The browser's `title` is gone on purpose: the tip is a Floating UI
    // panel in the detail view's own surface, not OS chrome.
    expect(patch).not.toHaveAttribute("title");
  });

  it("shows the meaning in a tooltip on hover", async () => {
    const user = userEvent.setup();
    render(<AvailabilityBadges runeword={named("Mosaic")} />);

    await user.hover(
      screen.getByRole("img", { name: en.availability.patchMeaning("2.6") }),
    );

    expect(
      await screen.findByRole("tooltip", {
        name: en.availability.patchMeaning("2.6"),
      }),
    ).toBeVisible();
  });

  it("renders nothing for a runeword predating patch tracking", () => {
    const untracked = runewords.find(
      (runeword) => !runeword.patch && runeword.note === undefined,
    );

    expect(untracked).toBeDefined();

    const { container } = render(
      <AvailabilityBadges runeword={untracked as Runeword} />,
    );

    expect(container).toBeEmptyDOMElement();
    expect(screen.queryAllByRole("img")).toEqual([]);
  });

  it("draws only patch and note badges across the whole dataset", () => {
    render(
      <ul>
        {runewords.map((runeword) => (
          <li key={runeword.name}>
            <AvailabilityBadges runeword={runeword} />
          </li>
        ))}
      </ul>,
    );

    const patches = runewords.filter(
      (runeword) => runeword.patch !== undefined,
    ).length;
    const notes = runewords.filter(
      (runeword) => runeword.note !== undefined,
    ).length;

    // The count is the whole assertion: a badge of any third kind — a ladder
    // marker returning, say — would push the total past what the two fields
    // account for, without any test needing to know its name.
    expect(screen.getAllByRole("img")).toHaveLength(patches + notes);
  });

  it("marks exactly the one runeword carrying a note", () => {
    const noted = runewords.filter((runeword) => runeword.note !== undefined);

    expect(noted.map((runeword) => runeword.name)).toEqual(["Mosaic"]);
  });
});

// The colour is asserted as the class the badge carries, not as a computed
// background: Tailwind's utilities are generated by the build and jsdom loads no
// stylesheet, so a computed colour here would read as empty for every badge
// whatever the class said.

describe("what a patch badge's colour says", () => {
  it("tells `3.0` apart from `1.10`", () => {
    expect(patchBadgeFor("3.0")).not.toBe(patchBadgeFor("1.10"));
  });

  it("gives `1.10` and `1.11` the same colour, as one era", () => {
    expect(patchBadgeFor("1.11")).toBe(patchBadgeFor("1.10"));
  });

  it("renders a patch with no colour decided plainly rather than wrongly", () => {
    render(
      <AvailabilityBadges runeword={{ ...named("Mosaic"), patch: "3.1" }} />,
    );

    const badge = screen.getByRole("img", {
      name: en.availability.patchMeaning("3.1"),
    });

    // Still a badge, still carrying its full meaning — just no background. The
    // missing entry should read as a decision nobody has taken yet.
    expect(badge).toHaveTextContent("3.1");
    expect([...badge.classList].filter(isBackground)).toEqual([]);
  });

  it("keeps the meaning in words whatever the colour is", () => {
    render(<AvailabilityBadges runeword={named("Mosaic")} />);

    const badge = screen.getByRole("img", {
      name: en.availability.patchMeaning("2.6"),
    });

    // The colour is a second channel over a meaning already stated, never the
    // only one. A badge whose colour cannot be seen is still readable.
    expect(badge).toHaveAccessibleName(en.availability.patchMeaning("2.6"));
  });
});

/** The background class the badge for a given patch value carries. */
function patchBadgeFor(patch: string) {
  const { unmount } = render(
    <AvailabilityBadges runeword={{ ...named("Mosaic"), patch }} />,
  );

  const classes = [
    ...screen.getByRole("img", { name: en.availability.patchMeaning(patch) })
      .classList,
  ].filter(isBackground);

  unmount();

  expect(classes).toHaveLength(1);

  return classes[0];
}

function isBackground(className: string) {
  return className.startsWith("bg-");
}

function named(name: string) {
  const found = runewords.find((runeword) => runeword.name === name);

  if (!found) throw new Error(`No runeword named ${name}`);

  return found;
}
